/* Kit Sosocial — textos en castellano (es) y catalán (ca) */
(function (KS) {
  KS.I18N = {
    es: {
      tab_diccionario: 'Diccionario', tab_piano: 'Piano', tab_guitarra: 'Guitarra', tab_bajo: 'Bajo', tab_metronomo: 'Metrónomo',
      progresion: 'Progresión', add_chord: '+ Acorde', remove_chord: 'Quitar acorde', chord_n: 'Acorde {n}',
      examples: 'Ejemplos', note_names: 'Notas', nn_lat: 'Do Re Mi', nn_en: 'C D E', nn_both: 'Las dos',
      share: 'Compartir', copied: 'Enlace copiado', copy_manual: 'Copia este enlace:',
      err_empty: 'Escribe un acorde', err_unknown: 'No reconozco este acorde', err_type: 'Tipo «{x}» no reconocido',
      fix_chords: 'Corrige los acordes marcados en rojo para ver las opciones.',
      con_bajo: ' con bajo en {n}', metro_play: 'Arrancar o parar el metrónomo', bpm_down: 'Más lento', bpm_up: 'Más rápido',
      play: '▶ Escuchar', stop: '■ Parar',
      common_title: 'Notas comunes', common_desc: 'Qué notas comparte cada acorde con el siguiente. La flecha final indica la vuelta al principio.', none: 'ninguna',
      legend_note: 'Nota del acorde', legend_common: 'Nota común con el acorde anterior', legend_bass: 'Bajo (mano izquierda)',
      held: '{n} se queda', up: '{a} sube a {b}', down: '{a} baja a {b}', start_point: 'Punto de partida', semitones: '{n} semitonos',
      inv_0: 'Fundamental', inv_1: '1ª inversión', inv_2: '2ª inversión', inv_3: '3ª inversión', inv_4: '4ª inversión',
      invs_0: 'Fund.', invs_1: '1ª', invs_2: '2ª', invs_3: '3ª', invs_4: '4ª',
      piano_desc: 'Cómo tocar la progresión en el teclado moviendo la mano lo mínimo. Pulsa cualquier teclado para escucharlo.',
      level: 'Nivel', p_l1: 'Posición fundamental', p_l1d: 'Todos los acordes con la fundamental abajo',
      p_l2: 'Inversiones', p_l2d: 'Tríadas en la inversión más cercana', p_l3: 'Acordes completos', p_l3d: 'Séptimas y más, con mano izquierda',
      lh: 'Mano izquierda: tocar el bajo', bars_per_chord: 'Compases por acorde', loop: 'Repetir', click_on: 'Con metrónomo',
      options: 'Opciones para tocarlo', options_desc: 'Cada opción empieza el primer acorde en una inversión diferente y busca el camino más corto. La barra indica cuánto se mueve la mano: cuanto más corta, más fácil.',
      starting: 'Empezando {c} en {inv}', all_root: 'Todos en posición fundamental', best: 'Menos movimiento',
      root_only_title: 'En posición fundamental', root_only_desc: 'Así se toca con todos los acordes en posición fundamental. Cuando lo domines, prueba el nivel 2 y compara cuánto se mueve la mano.',
      custom: 'Tu camino', custom_desc: 'Elige la inversión de cada acorde con los botones y compara el movimiento con las opciones de arriba.',
      your_version: 'Tu versión', same_best: 'igual que la recomendada', best_is: 'la recomendada: {n}',
      all_inv: 'Todas las inversiones de cada acorde', all_inv_desc: 'En naranja, las notas que comparte con el acorde anterior. El primero se compara con el último, como si la canción volviera a empezar.',
      simplified: 'como tríada', bass_lbl: 'bajo: {n}',
      m_start: '▶ Empezar', m_stop: '■ Parar', m_tap: 'Marcar tempo', m_tap_hint: 'Toca al ritmo',
      m_sig: 'Compás', m_sub: 'Subdivisión', sub_1: 'Negras', sub_2: 'Corcheas', sub_3: 'Tresillos', sub_4: 'Semicorcheas',
      m_accent: 'Acentuar el primer tiempo', m_countin: 'Cuenta de entrada (1 compás)',
      m_trainer: 'Entrenador de velocidad', m_trainer_desc: 'Sube la velocidad poco a poco mientras tocas.',
      m_to: 'Hasta', m_step: 'subir', m_every: 'cada', m_bars: 'compases', m_68: 'En 6/8 y 12/8 cada pulso es una corchea.',
      count_in: 'Preparados…', trainer_status: 'Entrenador: {a} → {b} BPM',
      soon: 'Próximamente', phase: 'Fase {n}',
      soon_dicc: 'El diccionario interactivo de notas y acordes en castellano y catalán, con mástiles y teclado que suenan al tocarlos.',
      soon_guit: 'Diagramas de acordes por niveles (al aire, cejilla, tríadas y acordes de 4 notas) con el camino más cómodo entre acordes y las notas comunes marcadas.',
      soon_bajo: 'Todas las posiciones de cada nota en formato C3T3 (cuerda 3, traste 3), el camino más corto entre acordes y niveles hasta las notas de paso.',
      bajo_desc: 'Dónde tocar cada nota en el mástil y cómo ir de un acorde al siguiente moviendo la mano lo mínimo.',
      pos_legend: '= cuerda 3, traste 3. La cuerda 1 es la más fina (G) y la 4 la más gruesa (E).',
      b_l1: 'Fundamental', b_l1d: 'Solo la nota que da nombre al acorde',
      b_l2: 'Fundamental, quinta y octava', b_l2d: 'El patrón 1 · 5 · 8 · 5',
      b_l3: 'Notas del acorde', b_l3d: 'Arpegio 1 · 3 · 5 · 8',
      b_l4: 'Notas de paso', b_l4d: 'El último pulso lleva al siguiente acorde',
      b_up8: 'Sonido una octava más aguda (se oye mejor en el móvil)',
      b_options_desc: 'Cada opción empieza el primer acorde en una posición distinta del mástil y busca el camino con menos desplazamiento de la mano.',
      b_start: 'Empezando en {p}', frets_moved: '{n} trastes de desplazamiento',
      hand_open: 'Cuerda al aire: la mano no se mueve', hand_same: 'La mano se queda en el traste {f}',
      hand_move: 'La mano se mueve {n} trastes', hand_move1: 'La mano se mueve 1 traste',
      b_custom_desc: 'Elige tú la posición de cada acorde y compara el desplazamiento con las opciones de arriba.',
      b_where: 'Dónde está cada nota', b_where_desc: 'Todas las posiciones de la nota del bajo de cada acorde entre los trastes 0 y 12. Pulsa una para escucharla.',
      tab: 'Tablatura', tab_desc: 'Cada línea es una cuerda (arriba la 1, G) y el número es el traste que se pisa.',
      slash_note: 'el bajo toca {n}', pattern: 'Patrón',
      legend_root: 'Nota del bajo (1)', legend_tones: 'Otras notas del acorde (3, 5, 8)', legend_app: 'Nota de paso (→)', legend_alt: 'Otras posiciones de la misma nota',
      g_desc: 'Diagramas de cada acorde por niveles y el camino más cómodo de uno a otro.',
      g_levels_hint: 'Puedes marcar varios niveles a la vez: la app elige entre todos los diagramas de esos niveles.',
      g_l1: 'Al aire', g_l1d: 'Acordes abiertos de primera posición',
      g_l2: 'Cejilla', g_l2d: 'Formas de Mi (raíz en la 6ª) y de La (raíz en la 5ª)',
      g_l3: 'Tríadas', g_l3d: 'Tres cuerdas, con sus inversiones',
      g_l4: 'Acordes de 4 notas', g_l4d: 'Séptimas en cuatro cuerdas',
      type_open: 'Al aire', type_E: 'Cejilla forma de Mi', type_A: 'Cejilla forma de La', type_tri: 'Tríada, cuerdas {s}', type_4: 'Cuerdas {s}',
      g_diag_help: 'Cómo leer el diagrama: las líneas verticales son las cuerdas (la 6ª, E grave, a la izquierda). Los números son los dedos: 1 índice, 2 medio, 3 anular, 4 meñique y P pulgar. O = cuerda al aire, X = no se toca, T5 = el diagrama empieza en el traste 5.',
      g_options_desc: 'Cada opción empieza el primer acorde con un diagrama distinto y busca el camino con menos movimiento. En naranja, las notas que comparte con el acorde anterior.',
      held_fingers1: '1 dedo se queda en su sitio', held_fingers: '{n} dedos se quedan en su sitio', g_same_zone: 'La mano se queda en la misma zona',
      g_custom_desc: 'Elige el diagrama de cada acorde y compara el movimiento con las opciones de arriba.',
      g_all: 'Todos los diagramas de cada acorde', g_all_desc: 'Según los niveles elegidos. Pulsa un diagrama para escucharlo.',
      g_outlevel: 'fuera de los niveles elegidos', g_bass_should: 'el bajo debería ser {n}',
      g_strum: 'Rasgueo', strum_bar: 'Uno por acorde', strum_beat: 'En cada pulso', g_choose: 'Diagrama',
      support_text: 'Kit Sosocial es gratuito. Si te resulta útil, puedes apoyar el proyecto.', support_btn: 'Apoyar en Ko-fi',
      lock_title: 'Introduce tu código', lock_desc: 'Kit Sosocial es para el alumnado de las clases. Pide el código a tu profesor o profesora.',
      lock_btn: 'Entrar', lock_err: 'Ese código no es correcto. Revísalo o pídelo de nuevo.', lock_expired: 'Tu código ha caducado. Pide uno nuevo a tu profesor o profesora.',
      lock_support: '¿Te gusta el proyecto? Apóyalo en Ko-fi', logout: 'Cambiar de código',
      footer: 'Kit Sosocial · herramientas para las clases de música'
    },
    ca: {
      tab_diccionario: 'Diccionari', tab_piano: 'Piano', tab_guitarra: 'Guitarra', tab_bajo: 'Baix', tab_metronomo: 'Metrònom',
      progresion: 'Progressió', add_chord: '+ Acord', remove_chord: 'Treure acord', chord_n: 'Acord {n}',
      examples: 'Exemples', note_names: 'Notes', nn_lat: 'Do Re Mi', nn_en: 'C D E', nn_both: 'Les dues',
      share: 'Compartir', copied: 'Enllaç copiat', copy_manual: 'Copia aquest enllaç:',
      err_empty: 'Escriu un acord', err_unknown: 'No reconec aquest acord', err_type: 'Tipus «{x}» no reconegut',
      fix_chords: 'Corregeix els acords marcats en vermell per veure les opcions.',
      con_bajo: ' amb baix en {n}', metro_play: 'Engegar o aturar el metrònom', bpm_down: 'Més lent', bpm_up: 'Més ràpid',
      play: '▶ Escoltar', stop: '■ Aturar',
      common_title: 'Notes comunes', common_desc: 'Quines notes comparteix cada acord amb el següent. La fletxa final indica la tornada al principi.', none: 'cap',
      legend_note: "Nota de l'acord", legend_common: "Nota comuna amb l'acord anterior", legend_bass: 'Baix (mà esquerra)',
      held: '{n} es queda', up: '{a} puja a {b}', down: '{a} baixa a {b}', start_point: 'Punt de partida', semitones: '{n} semitons',
      inv_0: 'Fonamental', inv_1: '1a inversió', inv_2: '2a inversió', inv_3: '3a inversió', inv_4: '4a inversió',
      invs_0: 'Fon.', invs_1: '1a', invs_2: '2a', invs_3: '3a', invs_4: '4a',
      piano_desc: 'Com tocar la progressió al teclat movent la mà el mínim. Prem qualsevol teclat per escoltar-lo.',
      level: 'Nivell', p_l1: 'Posició fonamental', p_l1d: 'Tots els acords amb la fonamental a baix',
      p_l2: 'Inversions', p_l2d: 'Tríades en la inversió més propera', p_l3: 'Acords complets', p_l3d: 'Setenes i més, amb mà esquerra',
      lh: 'Mà esquerra: tocar el baix', bars_per_chord: 'Compassos per acord', loop: 'Repetir', click_on: 'Amb metrònom',
      options: 'Opcions per tocar-ho', options_desc: 'Cada opció comença el primer acord en una inversió diferent i busca el camí més curt. La barra indica quant es mou la mà: com més curta, més fàcil.',
      starting: 'Començant {c} en {inv}', all_root: 'Tots en posició fonamental', best: 'Menys moviment',
      root_only_title: 'En posició fonamental', root_only_desc: 'Així es toca amb tots els acords en posició fonamental. Quan ho dominis, prova el nivell 2 i compara quant es mou la mà.',
      custom: 'El teu camí', custom_desc: "Tria la inversió de cada acord amb els botons i compara el moviment amb les opcions de dalt.",
      your_version: 'La teva versió', same_best: 'igual que la recomanada', best_is: 'la recomanada: {n}',
      all_inv: 'Totes les inversions de cada acord', all_inv_desc: "En taronja, les notes que comparteix amb l'acord anterior. El primer es compara amb l'últim, com si la cançó tornés a començar.",
      simplified: 'com a tríada', bass_lbl: 'baix: {n}',
      m_start: '▶ Començar', m_stop: '■ Aturar', m_tap: 'Marcar tempo', m_tap_hint: 'Toca al ritme',
      m_sig: 'Compàs', m_sub: 'Subdivisió', sub_1: 'Negres', sub_2: 'Corxeres', sub_3: 'Tresets', sub_4: 'Semicorxeres',
      m_accent: 'Accentuar el primer temps', m_countin: "Compte d'entrada (1 compàs)",
      m_trainer: 'Entrenador de velocitat', m_trainer_desc: 'Puja la velocitat de mica en mica mentre toques.',
      m_to: 'Fins a', m_step: 'pujar', m_every: 'cada', m_bars: 'compassos', m_68: 'En 6/8 i 12/8 cada pols és una corxera.',
      count_in: 'Preparats…', trainer_status: 'Entrenador: {a} → {b} BPM',
      soon: 'Properament', phase: 'Fase {n}',
      soon_dicc: "El diccionari interactiu de notes i acords en castellà i català, amb mànecs i teclat que sonen quan els toques.",
      soon_guit: "Diagrames d'acords per nivells (a l'aire, cejilla, tríades i acords de 4 notes) amb el camí més còmode entre acords i les notes comunes marcades.",
      soon_bajo: 'Totes les posicions de cada nota en format C3T3 (corda 3, trast 3), el camí més curt entre acords i nivells fins a les notes de pas.',
      bajo_desc: "On tocar cada nota al mànec i com anar d'un acord al següent movent la mà el mínim.",
      pos_legend: '= corda 3, trast 3. La corda 1 és la més fina (G) i la 4 la més gruixuda (E).',
      b_l1: 'Fonamental', b_l1d: "Només la nota que dona nom a l'acord",
      b_l2: 'Fonamental, cinquena i octava', b_l2d: 'El patró 1 · 5 · 8 · 5',
      b_l3: "Notes de l'acord", b_l3d: 'Arpegi 1 · 3 · 5 · 8',
      b_l4: 'Notes de pas', b_l4d: "L'últim pols porta al següent acord",
      b_up8: "So una octava més aguda (s'escolta millor al mòbil)",
      b_options_desc: 'Cada opció comença el primer acord en una posició diferent del mànec i busca el camí amb menys desplaçament de la mà.',
      b_start: 'Començant a {p}', frets_moved: '{n} trastos de desplaçament',
      hand_open: "Corda a l'aire: la mà no es mou", hand_same: 'La mà es queda al trast {f}',
      hand_move: 'La mà es mou {n} trastos', hand_move1: 'La mà es mou 1 trast',
      b_custom_desc: 'Tria tu la posició de cada acord i compara el desplaçament amb les opcions de dalt.',
      b_where: 'On és cada nota', b_where_desc: "Totes les posicions de la nota del baix de cada acord entre els trastos 0 i 12. Prem-ne una per escoltar-la.",
      tab: 'Tabulatura', tab_desc: 'Cada línia és una corda (a dalt la 1, G) i el número és el trast que es trepitja.',
      slash_note: 'el baix toca {n}', pattern: 'Patró',
      legend_root: 'Nota del baix (1)', legend_tones: "Altres notes de l'acord (3, 5, 8)", legend_app: 'Nota de pas (→)', legend_alt: 'Altres posicions de la mateixa nota',
      g_desc: "Diagrames de cada acord per nivells i el camí més còmode d'un a l'altre.",
      g_levels_hint: "Pots marcar diversos nivells alhora: l'app tria entre tots els diagrames d'aquests nivells.",
      g_l1: "A l'aire", g_l1d: 'Acords oberts de primera posició',
      g_l2: 'Cejilla (barré)', g_l2d: 'Formes de Mi (arrel a la 6a) i de La (arrel a la 5a)',
      g_l3: 'Tríades', g_l3d: 'Tres cordes, amb les seves inversions',
      g_l4: 'Acords de 4 notes', g_l4d: 'Setenes en quatre cordes',
      type_open: "A l'aire", type_E: 'Barré forma de Mi', type_A: 'Barré forma de La', type_tri: 'Tríada, cordes {s}', type_4: 'Cordes {s}',
      g_diag_help: "Com llegir el diagrama: les línies verticals són les cordes (la 6a, E greu, a l'esquerra). Els números són els dits: 1 índex, 2 del mig, 3 anular, 4 petit i P polze. O = corda a l'aire, X = no es toca, T5 = el diagrama comença al trast 5.",
      g_options_desc: "Cada opció comença el primer acord amb un diagrama diferent i busca el camí amb menys moviment. En taronja, les notes que comparteix amb l'acord anterior.",
      held_fingers1: '1 dit es queda al seu lloc', held_fingers: '{n} dits es queden al seu lloc', g_same_zone: 'La mà es queda a la mateixa zona',
      g_custom_desc: "Tria el diagrama de cada acord i compara el moviment amb les opcions de dalt.",
      g_all: 'Tots els diagrames de cada acord', g_all_desc: 'Segons els nivells triats. Prem un diagrama per escoltar-lo.',
      g_outlevel: 'fora dels nivells triats', g_bass_should: 'el baix hauria de ser {n}',
      g_strum: 'Rasgueig', strum_bar: 'Un per acord', strum_beat: 'A cada pols', g_choose: 'Diagrama',
      support_text: 'Kit Sosocial és gratuït. Si et resulta útil, pots donar suport al projecte.', support_btn: 'Donar suport a Ko-fi',
      lock_title: 'Introdueix el teu codi', lock_desc: "Kit Sosocial és per a l'alumnat de les classes. Demana el codi al teu professor o professora.",
      lock_btn: 'Entrar', lock_err: "Aquest codi no és correcte. Revisa'l o demana'l de nou.", lock_expired: "El teu codi ha caducat. Demana'n un de nou al teu professor o professora.",
      lock_support: "T'agrada el projecte? Dona-li suport a Ko-fi", logout: 'Canviar de codi',
      footer: 'Kit Sosocial · eines per a les classes de música'
    }
  };

  KS.t = (key, vars) => {
    const lang = KS.I18N[KS.state.lang] || KS.I18N.es;
    let s = (key in lang) ? lang[key] : (key in KS.I18N.es ? KS.I18N.es[key] : key);
    if (vars) for (const k in vars) s = s.split('{' + k + '}').join(vars[k]);
    return s;
  };

  KS.applyI18n = () => {
    document.documentElement.lang = KS.state.lang;
    document.querySelectorAll('[data-i18n]').forEach(el => { el.textContent = KS.t(el.dataset.i18n); });
    document.querySelectorAll('[data-i18n-aria]').forEach(el => { el.setAttribute('aria-label', KS.t(el.dataset.i18nAria)); });
  };
})(window.KS);
